name: Deploy to Cloud Platforms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r web_app/requirements.txt
        pip install -e ".[dev]"
    
    - name: Run tests
      run: |
        pytest tests/ -v
    
    - name: Run validation suite
      run: |
        python -m krippendorff_alpha.validation
    
    - name: Test web app
      run: |
        streamlit run web_app/app.py --server.headless=true &
        sleep 10
        curl -f http://localhost:8501/_stcore/health || exit 1

  docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          wildboars/krippendorff-alpha:latest
          wildboars/krippendorff-alpha:${{ github.sha }}
        platforms: linux/amd64,linux/arm64

  deploy-streamlit-cloud:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Streamlit Cloud
      run: |
        echo "Streamlit Cloud deployment triggered automatically on push to main"
        echo "Visit: https://share.streamlit.io/ to manage deployment"

  deploy-heroku:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.14
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "krippendorff-alpha-calculator"
        heroku_email: ${{ secrets.HEROKU_EMAIL }}
        dockerfile: "Dockerfile"